#!/usr/bin/python
# resolve ftracer hex addresses
# fresolve elf-binary
# only works for a single binary, no shared libraries
import bisect
import subprocess
import sys
import re

# must match printf field size used in ftracer.c
FIELDSIZE = 25

if len(sys.argv) < 2:
    print "usage: fresolve elf-executable < ftracer_log"
    sys.exit(1)

pipe = subprocess.Popen("nm  " + sys.argv[1],  shell=True,
                        stdout=subprocess.PIPE).stdout
symtab = []
adresses = []
max = 0
for l in pipe:
	m = re.match(r"^([0-9a-f]+) \S (\w+)", l)
	if m:
                val = int(m.group(1), 16)
                if val > max:
                    max = val
                pos = bisect.bisect_left(adresses, val)
                adresses.insert(pos, val)
		symtab.insert(pos, m.group(2))

for l in sys.stdin:
	f = l.split()
	if len(f) < 3 or not re.match("[0-9a-f]+", f[2]):
                print
	else:
                adr = int(f[2], 16)
                if adr > max + 1000:
                        print
                        continue
		n = bisect.bisect_left(adresses, adr) - 1
		if n >= len(adresses):
			print
			continue
		sym = symtab[n]
                print re.sub(f[2] + " *", "%-*s" % (FIELDSIZE, symtab[n]), l),

