#!/bin/sh
# frun executable arguments
# run executable with ftracer (must be already linked in) and resolve
# static addresses from main binary`
case "$0" in
*/*) FRESOLVE=`dirname $0`/fresolve ;;
*)   FRESOLVE=fresolve ;;
esac
FTRACER=1 "$@" 2>&1 | $FRESOLVE $1
