#!/usr/bin/python
# strip output log to easily checkable format
# remove time stamps, offsets
import sys, string, re

t = sys.stdin.readline()
tslen = string.find(t, "CALLER")

for l in sys.stdin:
    l = l[20:]
    l = l.replace("->","")
    l = re.sub(r'\+ \d+','', l)
    l = re.sub(r'\s+', ' ', l)
    l = re.sub(r'^\s', '', l)
    print l
